from itertools import count

print(
    """Triangle, pentagonal, and hexagonal numbers are generated by the
following formulae:
    Triangle    T{n}=n(n+1)/2   1, 3, 6, 10, 15, ...
    Pentagonal  P{n}=n(3n - 1)/2    1, 5, 12, 22, 35, ...
    Hexagonal   H{n}=n(2n - 1)  1, 6, 15, 28, 45, ...
It can be verified that T{285} = P{165} = H{143} = 40755
Find the next triangle number that is also pentagonal and hexagonal.

expected result: 1533776805
"""
)

arr = [i*(3*i-1)//2 for i in range(80_000)]

def search(val: int, low=1, high=79_999) -> bool:
    if high < low:
        return False    
    global arr
    if arr[mid := low + (high-low)//2] > val:
        return search(val, low, mid-1)
    elif arr[mid] < val:
        return search(val, mid+1, high)
    return True

for i in count(144):
    if search(res := i*(2*i-1)):
        print("result:", res)
        break
